//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BlastOutput2_report" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Report"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BlastOutput2_error" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Err"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blastOutput2Report",
    "blastOutput2Error"
})
@XmlRootElement(name = "BlastOutput2")
public class BlastOutput2 {

    @XmlElement(name = "BlastOutput2_report")
    protected BlastOutput2 .BlastOutput2Report blastOutput2Report;
    @XmlElement(name = "BlastOutput2_error")
    protected BlastOutput2 .BlastOutput2Error blastOutput2Error;

    /**
     * Gets the value of the blastOutput2Report property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutput2 .BlastOutput2Report }
     *     
     */
    public BlastOutput2 .BlastOutput2Report getBlastOutput2Report() {
        return blastOutput2Report;
    }

    /**
     * Sets the value of the blastOutput2Report property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutput2 .BlastOutput2Report }
     *     
     */
    public void setBlastOutput2Report(BlastOutput2 .BlastOutput2Report value) {
        this.blastOutput2Report = value;
    }

    /**
     * Gets the value of the blastOutput2Error property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutput2 .BlastOutput2Error }
     *     
     */
    public BlastOutput2 .BlastOutput2Error getBlastOutput2Error() {
        return blastOutput2Error;
    }

    /**
     * Sets the value of the blastOutput2Error property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutput2 .BlastOutput2Error }
     *     
     */
    public void setBlastOutput2Error(BlastOutput2 .BlastOutput2Error value) {
        this.blastOutput2Error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Err"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "err"
    })
    public static class BlastOutput2Error {

        @XmlElement(name = "Err", required = true)
        protected Err err;

        /**
         * Gets the value of the err property.
         * 
         * @return
         *     possible object is
         *     {@link Err }
         *     
         */
        public Err getErr() {
            return err;
        }

        /**
         * Sets the value of the err property.
         * 
         * @param value
         *     allowed object is
         *     {@link Err }
         *     
         */
        public void setErr(Err value) {
            this.err = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Report"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "report"
    })
    public static class BlastOutput2Report {

        @XmlElement(name = "Report", required = true)
        protected Report report;

        /**
         * Gets the value of the report property.
         * 
         * @return
         *     possible object is
         *     {@link Report }
         *     
         */
        public Report getReport() {
            return report;
        }

        /**
         * Sets the value of the report property.
         * 
         * @param value
         *     allowed object is
         *     {@link Report }
         *     
         */
        public void setReport(Report value) {
            this.report = value;
        }

    }

}
