//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Hit_num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Hit_description">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}HitDescr"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Hit_len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Hit_hsps" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hsp"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hitNum",
    "hitDescription",
    "hitLen",
    "hitHsps"
})
@XmlRootElement(name = "Hit")
public class Hit {

    @XmlElement(name = "Hit_num", required = true)
    protected BigInteger hitNum;
    @XmlElement(name = "Hit_description", required = true)
    protected Hit.HitDescription hitDescription;
    @XmlElement(name = "Hit_len", required = true)
    protected BigInteger hitLen;
    @XmlElement(name = "Hit_hsps")
    protected Hit.HitHsps hitHsps;

    /**
     * Gets the value of the hitNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHitNum() {
        return hitNum;
    }

    /**
     * Sets the value of the hitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHitNum(BigInteger value) {
        this.hitNum = value;
    }

    /**
     * Gets the value of the hitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Hit.HitDescription }
     *     
     */
    public Hit.HitDescription getHitDescription() {
        return hitDescription;
    }

    /**
     * Sets the value of the hitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hit.HitDescription }
     *     
     */
    public void setHitDescription(Hit.HitDescription value) {
        this.hitDescription = value;
    }

    /**
     * Gets the value of the hitLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHitLen() {
        return hitLen;
    }

    /**
     * Sets the value of the hitLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHitLen(BigInteger value) {
        this.hitLen = value;
    }

    /**
     * Gets the value of the hitHsps property.
     * 
     * @return
     *     possible object is
     *     {@link Hit.HitHsps }
     *     
     */
    public Hit.HitHsps getHitHsps() {
        return hitHsps;
    }

    /**
     * Sets the value of the hitHsps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hit.HitHsps }
     *     
     */
    public void setHitHsps(Hit.HitHsps value) {
        this.hitHsps = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}HitDescr"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hitDescr"
    })
    public static class HitDescription {

        @XmlElement(name = "HitDescr")
        protected List<HitDescr> hitDescr;

        /**
         * Gets the value of the hitDescr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hitDescr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHitDescr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HitDescr }
         * 
         * 
         */
        public List<HitDescr> getHitDescr() {
            if (hitDescr == null) {
                hitDescr = new ArrayList<HitDescr>();
            }
            return this.hitDescr;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hsp"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hsp"
    })
    public static class HitHsps {

        @XmlElement(name = "Hsp")
        protected List<Hsp> hsp;

        /**
         * Gets the value of the hsp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hsp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHsp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hsp }
         * 
         * 
         */
        public List<Hsp> getHsp() {
            if (hsp == null) {
                hsp = new ArrayList<Hsp>();
            }
            return this.hsp;
        }

    }

}
