//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HitDescr_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HitDescr_accession" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HitDescr_title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HitDescr_taxid" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="HitDescr_sciname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hitDescrId",
    "hitDescrAccession",
    "hitDescrTitle",
    "hitDescrTaxid",
    "hitDescrSciname"
})
@XmlRootElement(name = "HitDescr")
public class HitDescr {

    @XmlElement(name = "HitDescr_id", required = true)
    protected String hitDescrId;
    @XmlElement(name = "HitDescr_accession")
    protected String hitDescrAccession;
    @XmlElement(name = "HitDescr_title")
    protected String hitDescrTitle;
    @XmlElement(name = "HitDescr_taxid")
    protected BigInteger hitDescrTaxid;
    @XmlElement(name = "HitDescr_sciname")
    protected String hitDescrSciname;

    /**
     * Gets the value of the hitDescrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitDescrId() {
        return hitDescrId;
    }

    /**
     * Sets the value of the hitDescrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitDescrId(String value) {
        this.hitDescrId = value;
    }

    /**
     * Gets the value of the hitDescrAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitDescrAccession() {
        return hitDescrAccession;
    }

    /**
     * Sets the value of the hitDescrAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitDescrAccession(String value) {
        this.hitDescrAccession = value;
    }

    /**
     * Gets the value of the hitDescrTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitDescrTitle() {
        return hitDescrTitle;
    }

    /**
     * Sets the value of the hitDescrTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitDescrTitle(String value) {
        this.hitDescrTitle = value;
    }

    /**
     * Gets the value of the hitDescrTaxid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHitDescrTaxid() {
        return hitDescrTaxid;
    }

    /**
     * Sets the value of the hitDescrTaxid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHitDescrTaxid(BigInteger value) {
        this.hitDescrTaxid = value;
    }

    /**
     * Gets the value of the hitDescrSciname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitDescrSciname() {
        return hitDescrSciname;
    }

    /**
     * Sets the value of the hitDescrSciname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitDescrSciname(String value) {
        this.hitDescrSciname = value;
    }

}
