//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Iteration_iter-num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Iteration_search">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Search"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iterationIterNum",
    "iterationSearch"
})
@XmlRootElement(name = "Iteration")
public class Iteration {

    @XmlElement(name = "Iteration_iter-num", required = true)
    protected BigInteger iterationIterNum;
    @XmlElement(name = "Iteration_search", required = true)
    protected Iteration.IterationSearch iterationSearch;

    /**
     * Gets the value of the iterationIterNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIterationIterNum() {
        return iterationIterNum;
    }

    /**
     * Sets the value of the iterationIterNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIterationIterNum(BigInteger value) {
        this.iterationIterNum = value;
    }

    /**
     * Gets the value of the iterationSearch property.
     * 
     * @return
     *     possible object is
     *     {@link Iteration.IterationSearch }
     *     
     */
    public Iteration.IterationSearch getIterationSearch() {
        return iterationSearch;
    }

    /**
     * Sets the value of the iterationSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iteration.IterationSearch }
     *     
     */
    public void setIterationSearch(Iteration.IterationSearch value) {
        this.iterationSearch = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Search"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "search"
    })
    public static class IterationSearch {

        @XmlElement(name = "Search", required = true)
        protected Search search;

        /**
         * Gets the value of the search property.
         * 
         * @return
         *     possible object is
         *     {@link Search }
         *     
         */
        public Search getSearch() {
            return search;
        }

        /**
         * Sets the value of the search property.
         * 
         * @param value
         *     allowed object is
         *     {@link Search }
         *     
         */
        public void setSearch(Search value) {
            this.search = value;
        }

    }

}
