//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ncbi.nlm.nih.gov", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bzh.plealog.bioinfo.data.blast.loader.ncbi2;
