//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Report_program" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Report_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Report_reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Report_search-target">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Target"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Report_params">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Parameters"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Report_results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Results"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportProgram",
    "reportVersion",
    "reportReference",
    "reportSearchTarget",
    "reportParams",
    "reportResults"
})
@XmlRootElement(name = "Report")
public class Report {

    @XmlElement(name = "Report_program", required = true)
    protected String reportProgram;
    @XmlElement(name = "Report_version", required = true)
    protected String reportVersion;
    @XmlElement(name = "Report_reference", required = true)
    protected String reportReference;
    @XmlElement(name = "Report_search-target", required = true)
    protected Report.ReportSearchTarget reportSearchTarget;
    @XmlElement(name = "Report_params", required = true)
    protected Report.ReportParams reportParams;
    @XmlElement(name = "Report_results", required = true)
    protected Report.ReportResults reportResults;

    /**
     * Gets the value of the reportProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportProgram() {
        return reportProgram;
    }

    /**
     * Sets the value of the reportProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportProgram(String value) {
        this.reportProgram = value;
    }

    /**
     * Gets the value of the reportVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportVersion() {
        return reportVersion;
    }

    /**
     * Sets the value of the reportVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportVersion(String value) {
        this.reportVersion = value;
    }

    /**
     * Gets the value of the reportReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportReference() {
        return reportReference;
    }

    /**
     * Sets the value of the reportReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportReference(String value) {
        this.reportReference = value;
    }

    /**
     * Gets the value of the reportSearchTarget property.
     * 
     * @return
     *     possible object is
     *     {@link Report.ReportSearchTarget }
     *     
     */
    public Report.ReportSearchTarget getReportSearchTarget() {
        return reportSearchTarget;
    }

    /**
     * Sets the value of the reportSearchTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report.ReportSearchTarget }
     *     
     */
    public void setReportSearchTarget(Report.ReportSearchTarget value) {
        this.reportSearchTarget = value;
    }

    /**
     * Gets the value of the reportParams property.
     * 
     * @return
     *     possible object is
     *     {@link Report.ReportParams }
     *     
     */
    public Report.ReportParams getReportParams() {
        return reportParams;
    }

    /**
     * Sets the value of the reportParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report.ReportParams }
     *     
     */
    public void setReportParams(Report.ReportParams value) {
        this.reportParams = value;
    }

    /**
     * Gets the value of the reportResults property.
     * 
     * @return
     *     possible object is
     *     {@link Report.ReportResults }
     *     
     */
    public Report.ReportResults getReportResults() {
        return reportResults;
    }

    /**
     * Sets the value of the reportResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report.ReportResults }
     *     
     */
    public void setReportResults(Report.ReportResults value) {
        this.reportResults = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Parameters"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameters"
    })
    public static class ReportParams {

        @XmlElement(name = "Parameters", required = true)
        protected Parameters parameters;

        /**
         * Gets the value of the parameters property.
         * 
         * @return
         *     possible object is
         *     {@link Parameters }
         *     
         */
        public Parameters getParameters() {
            return parameters;
        }

        /**
         * Sets the value of the parameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Parameters }
         *     
         */
        public void setParameters(Parameters value) {
            this.parameters = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Results"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "results"
    })
    public static class ReportResults {

        @XmlElement(name = "Results", required = true)
        protected Results results;

        /**
         * Gets the value of the results property.
         * 
         * @return
         *     possible object is
         *     {@link Results }
         *     
         */
        public Results getResults() {
            return results;
        }

        /**
         * Sets the value of the results property.
         * 
         * @param value
         *     allowed object is
         *     {@link Results }
         *     
         */
        public void setResults(Results value) {
            this.results = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Target"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "target"
    })
    public static class ReportSearchTarget {

        @XmlElement(name = "Target", required = true)
        protected Target target;

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link Target }
         *     
         */
        public Target getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link Target }
         *     
         */
        public void setTarget(Target value) {
            this.target = value;
        }

    }

}
