//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Search_query-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Search_query-title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Search_query-len" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Search_query-masking" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Range"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Search_hits" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hit"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Search_stat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Search_message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchQueryId",
    "searchQueryTitle",
    "searchQueryLen",
    "searchQueryMasking",
    "searchHits",
    "searchStat",
    "searchMessage"
})
@XmlRootElement(name = "Search")
public class Search {

    @XmlElement(name = "Search_query-id")
    protected String searchQueryId;
    @XmlElement(name = "Search_query-title")
    protected String searchQueryTitle;
    @XmlElement(name = "Search_query-len")
    protected BigInteger searchQueryLen;
    @XmlElement(name = "Search_query-masking")
    protected Search.SearchQueryMasking searchQueryMasking;
    @XmlElement(name = "Search_hits")
    protected Search.SearchHits searchHits;
    @XmlElement(name = "Search_stat")
    protected Search.SearchStat searchStat;
    @XmlElement(name = "Search_message")
    protected String searchMessage;

    /**
     * Gets the value of the searchQueryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchQueryId() {
        return searchQueryId;
    }

    /**
     * Sets the value of the searchQueryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchQueryId(String value) {
        this.searchQueryId = value;
    }

    /**
     * Gets the value of the searchQueryTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchQueryTitle() {
        return searchQueryTitle;
    }

    /**
     * Sets the value of the searchQueryTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchQueryTitle(String value) {
        this.searchQueryTitle = value;
    }

    /**
     * Gets the value of the searchQueryLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSearchQueryLen() {
        return searchQueryLen;
    }

    /**
     * Sets the value of the searchQueryLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSearchQueryLen(BigInteger value) {
        this.searchQueryLen = value;
    }

    /**
     * Gets the value of the searchQueryMasking property.
     * 
     * @return
     *     possible object is
     *     {@link Search.SearchQueryMasking }
     *     
     */
    public Search.SearchQueryMasking getSearchQueryMasking() {
        return searchQueryMasking;
    }

    /**
     * Sets the value of the searchQueryMasking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search.SearchQueryMasking }
     *     
     */
    public void setSearchQueryMasking(Search.SearchQueryMasking value) {
        this.searchQueryMasking = value;
    }

    /**
     * Gets the value of the searchHits property.
     * 
     * @return
     *     possible object is
     *     {@link Search.SearchHits }
     *     
     */
    public Search.SearchHits getSearchHits() {
        return searchHits;
    }

    /**
     * Sets the value of the searchHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search.SearchHits }
     *     
     */
    public void setSearchHits(Search.SearchHits value) {
        this.searchHits = value;
    }

    /**
     * Gets the value of the searchStat property.
     * 
     * @return
     *     possible object is
     *     {@link Search.SearchStat }
     *     
     */
    public Search.SearchStat getSearchStat() {
        return searchStat;
    }

    /**
     * Sets the value of the searchStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search.SearchStat }
     *     
     */
    public void setSearchStat(Search.SearchStat value) {
        this.searchStat = value;
    }

    /**
     * Gets the value of the searchMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchMessage() {
        return searchMessage;
    }

    /**
     * Sets the value of the searchMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchMessage(String value) {
        this.searchMessage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hit"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hit"
    })
    public static class SearchHits {

        @XmlElement(name = "Hit")
        protected List<Hit> hit;

        /**
         * Gets the value of the hit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hit }
         * 
         * 
         */
        public List<Hit> getHit() {
            if (hit == null) {
                hit = new ArrayList<Hit>();
            }
            return this.hit;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Range"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "range"
    })
    public static class SearchQueryMasking {

        @XmlElement(name = "Range")
        protected List<Range> range;

        /**
         * Gets the value of the range property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the range property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Range }
         * 
         * 
         */
        public List<Range> getRange() {
            if (range == null) {
                range = new ArrayList<Range>();
            }
            return this.range;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statistics"
    })
    public static class SearchStat {

        @XmlElement(name = "Statistics", required = true)
        protected Statistics statistics;

        /**
         * Gets the value of the statistics property.
         * 
         * @return
         *     possible object is
         *     {@link Statistics }
         *     
         */
        public Statistics getStatistics() {
            return statistics;
        }

        /**
         * Sets the value of the statistics property.
         * 
         * @param value
         *     allowed object is
         *     {@link Statistics }
         *     
         */
        public void setStatistics(Statistics value) {
            this.statistics = value;
        }

    }

}
