//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 12:48:55 PM GMT 
//


package bzh.plealog.bioinfo.data.blast.loader.ncbi2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Statistics_db-num" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Statistics_db-len" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Statistics_hsp-len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Statistics_eff-space" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Statistics_kappa" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Statistics_lambda" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Statistics_entropy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statisticsDbNum",
    "statisticsDbLen",
    "statisticsHspLen",
    "statisticsEffSpace",
    "statisticsKappa",
    "statisticsLambda",
    "statisticsEntropy"
})
@XmlRootElement(name = "Statistics")
public class Statistics {

    @XmlElement(name = "Statistics_db-num")
    protected Long statisticsDbNum;
    @XmlElement(name = "Statistics_db-len")
    protected Long statisticsDbLen;
    @XmlElement(name = "Statistics_hsp-len", required = true)
    protected BigInteger statisticsHspLen;
    @XmlElement(name = "Statistics_eff-space")
    protected long statisticsEffSpace;
    @XmlElement(name = "Statistics_kappa")
    protected double statisticsKappa;
    @XmlElement(name = "Statistics_lambda")
    protected double statisticsLambda;
    @XmlElement(name = "Statistics_entropy")
    protected double statisticsEntropy;

    /**
     * Gets the value of the statisticsDbNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatisticsDbNum() {
        return statisticsDbNum;
    }

    /**
     * Sets the value of the statisticsDbNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatisticsDbNum(Long value) {
        this.statisticsDbNum = value;
    }

    /**
     * Gets the value of the statisticsDbLen property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatisticsDbLen() {
        return statisticsDbLen;
    }

    /**
     * Sets the value of the statisticsDbLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatisticsDbLen(Long value) {
        this.statisticsDbLen = value;
    }

    /**
     * Gets the value of the statisticsHspLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatisticsHspLen() {
        return statisticsHspLen;
    }

    /**
     * Sets the value of the statisticsHspLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatisticsHspLen(BigInteger value) {
        this.statisticsHspLen = value;
    }

    /**
     * Gets the value of the statisticsEffSpace property.
     * 
     */
    public long getStatisticsEffSpace() {
        return statisticsEffSpace;
    }

    /**
     * Sets the value of the statisticsEffSpace property.
     * 
     */
    public void setStatisticsEffSpace(long value) {
        this.statisticsEffSpace = value;
    }

    /**
     * Gets the value of the statisticsKappa property.
     * 
     */
    public double getStatisticsKappa() {
        return statisticsKappa;
    }

    /**
     * Sets the value of the statisticsKappa property.
     * 
     */
    public void setStatisticsKappa(double value) {
        this.statisticsKappa = value;
    }

    /**
     * Gets the value of the statisticsLambda property.
     * 
     */
    public double getStatisticsLambda() {
        return statisticsLambda;
    }

    /**
     * Sets the value of the statisticsLambda property.
     * 
     */
    public void setStatisticsLambda(double value) {
        this.statisticsLambda = value;
    }

    /**
     * Gets the value of the statisticsEntropy property.
     * 
     */
    public double getStatisticsEntropy() {
        return statisticsEntropy;
    }

    /**
     * Sets the value of the statisticsEntropy property.
     * 
     */
    public void setStatisticsEntropy(double value) {
        this.statisticsEntropy = value;
    }

}
